
# Arquivo de configuração DHCP

# Define o estilo de atualização do DDNS como "none", ou seja, desabilitado.
ddns-update-style none;

# Define o tempo padrão de concessão de endereço IP como 600 (10m) segundos.
default-lease-time 600;

# Define o tempo máximo de concessão de endereço IP como 7200 segundos.
max-lease-time 7200;

# Indica que este servidor DHCP é autoritativo para as configurações especificadas.
authoritative;

# Define uma sub-rede com endereço base 172.17.0.0 e máscara de sub-rede 255.255.255.0.
subnet 172.17.0.0 netmask 255.255.255.0 {

	# Define o intervalo de endereços IP que o servidor DHCP pode atribuir aos clientes dentro da sub-rede especificada.
    range 172.17.0.100 172.17.0.199;

	# Define o endereço do gateway padrão para os clientes DHCP como 172.17.0.1.
    option routers 172.17.0.1;

	# Define os servidores DNS que os clientes DHCP devem usar como 8.8.8.8 e 8.8.4.4 (servidores DNS do Google).
    option domain-name-servers 192.168.200.2,192.168.200.3;  

	# Define o endereço de broadcast para a sub-rede como 172.17.0.255.
    option broadcast-address 172.17.0.255;

#    deny unknown-clients;

}

#host PC-01 { 
#	hardware ethernet 08:00:27:F3:92:33;
#		fixed-address 172.17.0.150;
#}
